name: Dev environment CD to Azure Container App with Makefile

on:
  workflow_dispatch:
    inputs:
      image-tags-sha:
        description: 'GITHUB_SHA'
        type: string
        required: true

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: 'ca-api-dotnet'
  RESOURCE_GROUP: 'CONTAINER_APP_RG'

jobs:
  # CD task
  deploy:
    permissions:
      #   actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Log in to Azure
        # uses: azure/login@v1
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
          registryUrl: ${{ env.REGISTRY }}
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.WORKFLOW_TOKEN }}
          containerAppName: ${{ env.CONTAINER_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          environmentVariables: PORT=40000
